-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 11:25:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema allchwi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `allchwi` ;

-- -----------------------------------------------------
-- Schema allchwi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `allchwi` DEFAULT CHARACTER SET utf8 ;
USE `allchwi` ;

-- -----------------------------------------------------
-- Table `allchwi`.`member_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`member_login` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`member_login` (
  `ml_num` INT(11) NOT NULL AUTO_INCREMENT COMMENT '로그인번호',
  `id` VARCHAR(50) NOT NULL COMMENT '아이디\\n',
  `pwd` VARCHAR(45) NULL DEFAULT NULL COMMENT '비밀번호',
  `tutor_auth` INT(11) NULL DEFAULT NULL COMMENT '튜터여부\\n',
  `login_auth` INT(11) NULL DEFAULT NULL COMMENT '탈퇴여부\\n',
  `ml_regdate` TIMESTAMP NULL DEFAULT NULL COMMENT '등록일',
  `email_auth` CHAR(2) NULL DEFAULT NULL COMMENT '이메일 인증\\n',
  `kakaoUser` INT(11) NULL DEFAULT 0 COMMENT '카카오 회원 1\\\\n일반 회원 0',
  PRIMARY KEY (`ml_num`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8
COMMENT = '로그인테이블 ';


-- -----------------------------------------------------
-- Table `allchwi`.`big_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`big_category` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`big_category` (
  `bcategory_num` INT(11) NOT NULL AUTO_INCREMENT,
  `bcategory_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bcategory_num`))
ENGINE = InnoDB
AUTO_INCREMENT = 292
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`small_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`small_category` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`small_category` (
  `scategory_num` INT(11) NOT NULL AUTO_INCREMENT,
  `bcategory_num` INT(11) NOT NULL,
  `scategory_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`scategory_num`, `bcategory_num`),
  INDEX `fk_small_category_big_category1_idx` (`bcategory_num` ASC) VISIBLE,
  CONSTRAINT `fk_small_category_big_category1`
    FOREIGN KEY (`bcategory_num`)
    REFERENCES `allchwi`.`big_category` (`bcategory_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 497
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`big_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`big_location` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`big_location` (
  `bloc_num` INT(11) NOT NULL AUTO_INCREMENT,
  `bloc_name` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`bloc_num`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`small_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`small_location` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`small_location` (
  `sloc_num` INT(11) NOT NULL AUTO_INCREMENT,
  `bloc_num` INT(11) NOT NULL,
  `sloc_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`sloc_num`, `bloc_num`),
  INDEX `fk_small_location_big_location1_idx` (`bloc_num` ASC) VISIBLE,
  CONSTRAINT `fk_small_location_big_location1`
    FOREIGN KEY (`bloc_num`)
    REFERENCES `allchwi`.`big_location` (`bloc_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`profile_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`profile_img` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`profile_img` (
  `pro_num` INT(11) NOT NULL AUTO_INCREMENT,
  `pro_img` LONGBLOB NULL DEFAULT NULL,
  `pro_filename` VARCHAR(100) NULL DEFAULT NULL,
  `pro_regdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`pro_num`))
ENGINE = InnoDB
AUTO_INCREMENT = 90
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`class_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`class_info` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`class_info` (
  `class_num` INT(11) NOT NULL AUTO_INCREMENT,
  `ml_num` INT(11) NOT NULL,
  `scategory_num` INT(11) NOT NULL,
  `sloc_num` INT(11) NOT NULL,
  `pro_num` INT(11) NOT NULL,
  `tutor_nickname` VARCHAR(45) NULL,
  `tutor_phone` VARCHAR(50) NULL,
  `class_address` VARCHAR(100) NULL,
  `class_form` INT(11) NULL,
  `class_max` INT(11) NULL,
  `class_min` INT(11) NULL,
  `class_title` VARCHAR(200) NULL,
  `class_price` INT(11) NULL,
  `class_hour` INT(11) NOT NULL,
  `class_count` TEXT NULL,
  `tutor_about` TEXT NULL,
  `class_about` TEXT NULL,
  `class_target` TEXT NULL,
  `class_regdate` TIMESTAMP NULL,
  `class_auth` INT(11) NULL,
  `class_status` INT(11) NULL,
  PRIMARY KEY (`class_num`, `ml_num`, `scategory_num`, `sloc_num`),
  INDEX `fk_class_info_member_login1_idx` (`ml_num` ASC) VISIBLE,
  INDEX `fk_class_info_small_category1_idx` (`scategory_num` ASC) VISIBLE,
  INDEX `fk_class_info_small_location1_idx` (`sloc_num` ASC) VISIBLE,
  INDEX `fk_class_info_profile_img3_idx` (`pro_num` ASC) VISIBLE,
  CONSTRAINT `fk_class_info_member_login1`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_info_small_category1`
    FOREIGN KEY (`scategory_num`)
    REFERENCES `allchwi`.`small_category` (`scategory_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_info_small_location1`
    FOREIGN KEY (`sloc_num`)
    REFERENCES `allchwi`.`small_location` (`sloc_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_info_profile_img3`
    FOREIGN KEY (`pro_num`)
    REFERENCES `allchwi`.`profile_img` (`pro_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 145
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`community`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`community` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`community` (
  `commu_num` INT(11) NOT NULL AUTO_INCREMENT,
  `class_num` INT(11) NOT NULL,
  `commu_title` VARCHAR(300) NOT NULL,
  `commu_regdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`commu_num`, `class_num`),
  INDEX `fk_community_class_info1_idx` (`class_num` ASC) VISIBLE,
  CONSTRAINT `fk_community_class_info1`
    FOREIGN KEY (`class_num`)
    REFERENCES `allchwi`.`class_info` (`class_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`assignment` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`assignment` (
  `assign_num` INT(11) NOT NULL AUTO_INCREMENT,
  `commu_num` INT(11) NOT NULL,
  `assign_title` VARCHAR(50) NOT NULL,
  `assign_content` VARCHAR(100) NOT NULL,
  `assign_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`assign_num`, `commu_num`),
  INDEX `fk_assignment_community1_idx` (`commu_num` ASC) VISIBLE,
  CONSTRAINT `fk_assignment_community1`
    FOREIGN KEY (`commu_num`)
    REFERENCES `allchwi`.`community` (`commu_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`assign_submit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`assign_submit` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`assign_submit` (
  `sub_num` INT(11) NOT NULL AUTO_INCREMENT,
  `assign_num` INT(11) NOT NULL,
  `ml_num` INT(11) NOT NULL,
  `sub_content` VARCHAR(200) NOT NULL,
  `sub_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`sub_num`, `assign_num`, `ml_num`),
  INDEX `fk_assign_submit_assignment1_idx` (`assign_num` ASC) VISIBLE,
  INDEX `fk_assign_submit_member_login1_idx` (`ml_num` ASC) VISIBLE,
  CONSTRAINT `fk_assign_submit_assignment1`
    FOREIGN KEY (`assign_num`)
    REFERENCES `allchwi`.`assignment` (`assign_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assign_submit_member_login1`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`assign_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`assign_data` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`assign_data` (
  `assigndata_num` INT(11) NOT NULL AUTO_INCREMENT,
  `sub_num` INT(11) NOT NULL,
  `assign_orgFilename` VARCHAR(100) NOT NULL,
  `assign_saveFilename` VARCHAR(100) NOT NULL,
  `assigndata_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `assigndata_size` BIGINT(20) NOT NULL,
  PRIMARY KEY (`assigndata_num`, `sub_num`),
  INDEX `fk_assign_data_assign_submit1_idx` (`sub_num` ASC) VISIBLE,
  CONSTRAINT `fk_assign_data_assign_submit1`
    FOREIGN KEY (`sub_num`)
    REFERENCES `allchwi`.`assign_submit` (`sub_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`certificate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`certificate` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`certificate` (
  `certif_num` INT(11) NOT NULL AUTO_INCREMENT,
  `class_info_class_num` INT(11) NOT NULL,
  `certif_filename` VARCHAR(200) NOT NULL,
  `certif_file` LONGBLOB NOT NULL,
  `certif_name` VARCHAR(100) NOT NULL,
  `certif_regdate` TIMESTAMP NULL,
  PRIMARY KEY (`certif_num`),
  INDEX `fk_certificate_class_info2_idx` (`class_info_class_num` ASC) VISIBLE,
  CONSTRAINT `fk_certificate_class_info2`
    FOREIGN KEY (`class_info_class_num`)
    REFERENCES `allchwi`.`class_info` (`class_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`class_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`class_date` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`class_date` (
  `date_num` INT(11) NOT NULL AUTO_INCREMENT,
  `class_num` INT(11) NOT NULL,
  `class_date` TIMESTAMP NULL DEFAULT NULL,
  `class_startTime` VARCHAR(50) NULL DEFAULT NULL,
  `class_endTime` VARCHAR(50) NULL DEFAULT NULL,
  `class_comment` TEXT NULL DEFAULT NULL,
  `class_msg` TEXT NULL DEFAULT NULL,
  `class_month` INT(11) NULL DEFAULT NULL,
  `time_ref` INT(11) NULL DEFAULT NULL,
  `time_cnt` INT(11) NULL DEFAULT NULL,
  `date_regdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`date_num`, `class_num`),
  INDEX `fk_class_date_class_info1_idx` (`class_num` ASC) VISIBLE,
  CONSTRAINT `fk_class_date_class_info1`
    FOREIGN KEY (`class_num`)
    REFERENCES `allchwi`.`class_info` (`class_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 173
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`class_apply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`class_apply` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`class_apply` (
  `apply_num` INT(11) NOT NULL AUTO_INCREMENT,
  `date_num` INT(11) NOT NULL,
  `ml_num` INT(11) NOT NULL,
  `stu_lev` VARCHAR(45) NOT NULL,
  `stu_msg` VARCHAR(100) NOT NULL,
  `stu_phone` VARCHAR(45) NOT NULL,
  `apply_auth` CHAR(1) NOT NULL,
  `apply_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`apply_num`, `date_num`, `ml_num`),
  INDEX `fk_class_apply_class_date1_idx` (`date_num` ASC) VISIBLE,
  INDEX `fk_class_apply_member_login1_idx` (`ml_num` ASC) VISIBLE,
  CONSTRAINT `fk_class_apply_class_date1`
    FOREIGN KEY (`date_num`)
    REFERENCES `allchwi`.`class_date` (`date_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_apply_member_login1`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`class_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`class_img` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`class_img` (
  `cover_num` INT(11) NOT NULL AUTO_INCREMENT,
  `class_num` INT(11) NOT NULL,
  `cover_name` VARCHAR(100) NULL DEFAULT NULL,
  `cover_file` LONGBLOB NULL DEFAULT NULL,
  `cover_regdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`cover_num`),
  INDEX `fk_class_img_class_info2_idx` (`class_num` ASC) VISIBLE,
  CONSTRAINT `fk_class_img_class_info2`
    FOREIGN KEY (`class_num`)
    REFERENCES `allchwi`.`class_info` (`class_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`class_qna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`class_qna` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`class_qna` (
  `qna_num` INT(11) NOT NULL AUTO_INCREMENT,
  `ml_num` INT(11) NOT NULL,
  `class_num` INT(11) NOT NULL,
  `qna_content` VARCHAR(200) NOT NULL,
  `qna_ref` INT(11) NOT NULL,
  `qna_lev` INT(11) NOT NULL,
  `qna_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `qna_status` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`qna_num`, `ml_num`, `class_num`),
  INDEX `fk_class_qna_class_info1_idx` (`class_num` ASC) VISIBLE,
  INDEX `fk_class_qna_member_login1_idx` (`ml_num` ASC) VISIBLE,
  CONSTRAINT `fk_class_qna_class_info1`
    FOREIGN KEY (`class_num`)
    REFERENCES `allchwi`.`class_info` (`class_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_qna_member_login1`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 93
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`class_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`class_review` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`class_review` (
  `review_num` INT(11) NOT NULL AUTO_INCREMENT,
  `class_num` INT(11) NOT NULL,
  `ml_num` INT(11) NOT NULL,
  `curr_rating` INT(11) NOT NULL,
  `ready_rating` INT(11) NOT NULL,
  `kind_rating` INT(11) NOT NULL,
  `time_rating` INT(11) NOT NULL,
  `review_content` VARCHAR(200) NOT NULL,
  `review_status` INT(11) NOT NULL,
  `review_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`review_num`, `class_num`, `ml_num`),
  INDEX `fk_class_review_class_info1_idx` (`class_num` ASC) VISIBLE,
  INDEX `fk_class_review_member_login1_idx` (`ml_num` ASC) VISIBLE,
  CONSTRAINT `fk_class_review_class_info1`
    FOREIGN KEY (`class_num`)
    REFERENCES `allchwi`.`class_info` (`class_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_review_member_login1`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`commu_qna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`commu_qna` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`commu_qna` (
  `qna_num` INT(11) NOT NULL AUTO_INCREMENT,
  `commu_num` INT(11) NOT NULL,
  `ml_num` INT(11) NOT NULL,
  `qna_content` VARCHAR(300) NOT NULL,
  `qna_ref` INT(11) NOT NULL,
  `qna_lev` INT(11) NOT NULL,
  `qna_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`qna_num`, `commu_num`, `ml_num`),
  INDEX `fk_commu_qna_community1_idx` (`commu_num` ASC) VISIBLE,
  INDEX `fk_commu_qna_member_login1_idx` (`ml_num` ASC) VISIBLE,
  CONSTRAINT `fk_commu_qna_community1`
    FOREIGN KEY (`commu_num`)
    REFERENCES `allchwi`.`community` (`commu_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commu_qna_member_login1`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`curriculum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`curriculum` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`curriculum` (
  `curri_num` INT(11) NOT NULL AUTO_INCREMENT,
  `class_num` INT(11) NOT NULL,
  `curri_count` INT(11) NULL DEFAULT NULL,
  `curri_content` TEXT NULL DEFAULT NULL,
  `curri_regdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`curri_num`, `class_num`),
  INDEX `fk_curriculum_class_info1_idx` (`class_num` ASC) VISIBLE,
  CONSTRAINT `fk_curriculum_class_info1`
    FOREIGN KEY (`class_num`)
    REFERENCES `allchwi`.`class_info` (`class_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`member_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`member_info` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`member_info` (
  `mb_num` INT(11) NOT NULL AUTO_INCREMENT,
  `ml_num` INT(11) NOT NULL,
  `pro_num` INT(11) NOT NULL,
  `mb_name` VARCHAR(20) NULL DEFAULT NULL,
  `mb_phone` VARCHAR(20) NULL DEFAULT NULL,
  `mb_nickname` VARCHAR(50) NULL DEFAULT NULL,
  `mb_about` VARCHAR(600) NULL DEFAULT NULL,
  `mb_auth` INT(11) NULL DEFAULT NULL,
  `mb_reason` VARCHAR(100) NULL DEFAULT NULL,
  `mb_regdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`mb_num`, `ml_num`, `pro_num`),
  INDEX `fk_member_info_member_login_idx` (`ml_num` ASC) VISIBLE,
  INDEX `fk_member_info_profile_img1_idx` (`pro_num` ASC) VISIBLE,
  CONSTRAINT `fk_member_info_member_login`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_info_profile_img1`
    FOREIGN KEY (`pro_num`)
    REFERENCES `allchwi`.`profile_img` (`pro_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8
COMMENT = '회원정보';


-- -----------------------------------------------------
-- Table `allchwi`.`notice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`notice` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`notice` (
  `notice_num` INT(11) NOT NULL AUTO_INCREMENT,
  `commu_num` INT(11) NOT NULL,
  `class_num` INT(11) NULL DEFAULT NULL,
  `notice_title` VARCHAR(45) NULL DEFAULT NULL,
  `notice_content` VARCHAR(300) NULL DEFAULT NULL,
  `notice_view` INT(11) NULL DEFAULT NULL,
  `notice_regdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`notice_num`, `commu_num`),
  INDEX `fk_notice_community1_idx` (`commu_num` ASC) VISIBLE,
  CONSTRAINT `fk_notice_community1`
    FOREIGN KEY (`commu_num`)
    REFERENCES `allchwi`.`community` (`commu_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COMMENT = '커뮤니티 공지사항 테이블';


-- -----------------------------------------------------
-- Table `allchwi`.`online_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`online_class` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`online_class` (
  `online_num` INT(11) NOT NULL AUTO_INCREMENT,
  `commu_num` INT(11) NOT NULL,
  `online_title` VARCHAR(200) NULL DEFAULT NULL,
  `online_content` TEXT NULL DEFAULT NULL,
  `online_time` INT(11) NULL DEFAULT NULL,
  `online_file` VARCHAR(400) NULL DEFAULT NULL,
  `online_thumbnail` LONGBLOB NULL DEFAULT NULL,
  `online_regdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`online_num`, `commu_num`),
  INDEX `fk_online_class_community1_idx` (`commu_num` ASC) VISIBLE,
  CONSTRAINT `fk_online_class_community1`
    FOREIGN KEY (`commu_num`)
    REFERENCES `allchwi`.`community` (`commu_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`online_check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`online_check` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`online_check` (
  `check_num` INT(11) NOT NULL AUTO_INCREMENT,
  `ml_num` INT(11) NOT NULL,
  `online_num` INT(11) NOT NULL,
  `view_point` INT(11) NULL DEFAULT NULL,
  `view_regdate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`check_num`, `ml_num`, `online_num`),
  INDEX `fk_online_check_online_class1_idx` (`online_num` ASC) VISIBLE,
  INDEX `fk_online_check_member_login1_idx` (`ml_num` ASC) VISIBLE,
  CONSTRAINT `fk_online_check_online_class1`
    FOREIGN KEY (`online_num`)
    REFERENCES `allchwi`.`online_class` (`online_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_online_check_member_login1`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`payment` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`payment` (
  `pay_num` INT(11) NOT NULL AUTO_INCREMENT,
  `class_num` INT(11) NOT NULL,
  `ml_num` INT(11) NOT NULL,
  `apply_num` INT(11) NOT NULL,
  `pay_way` VARCHAR(45) NOT NULL,
  `final_price` INT(8) NOT NULL,
  `pay_point` INT(8) NOT NULL,
  `class_fee` INT(8) NOT NULL,
  `class_finish` INT(4) NOT NULL,
  `pay_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`pay_num`, `class_num`, `ml_num`, `apply_num`),
  INDEX `fk_payment_class_apply1_idx` (`apply_num` ASC) VISIBLE,
  INDEX `fk_payment_class_info1_idx` (`class_num` ASC) VISIBLE,
  INDEX `fk_payment_member_login1_idx` (`ml_num` ASC) VISIBLE,
  CONSTRAINT `fk_payment_class_apply1`
    FOREIGN KEY (`apply_num`)
    REFERENCES `allchwi`.`class_apply` (`apply_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_class_info1`
    FOREIGN KEY (`class_num`)
    REFERENCES `allchwi`.`class_info` (`class_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_member_login1`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = utf8
COMMENT = '결제정보';


-- -----------------------------------------------------
-- Table `allchwi`.`point`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`point` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`point` (
  `point_num` INT(11) NOT NULL AUTO_INCREMENT,
  `ml_num` INT(11) NOT NULL,
  `point` INT(11) NULL DEFAULT NULL,
  `point_name` VARCHAR(50) NULL DEFAULT NULL,
  `point_regdate` TIMESTAMP NULL DEFAULT NULL,
  `point_type` CHAR(1) NULL DEFAULT NULL COMMENT 'u -> use - 사용\\ns -> save - 적립',
  PRIMARY KEY (`point_num`, `ml_num`),
  INDEX `fk_point_member_login1_idx` (`ml_num` ASC) VISIBLE,
  CONSTRAINT `fk_point_member_login1`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8
COMMENT = '포인트';


-- -----------------------------------------------------
-- Table `allchwi`.`ref_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`ref_room` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`ref_room` (
  `room_num` INT(11) NOT NULL AUTO_INCREMENT,
  `commu_num` INT(11) NOT NULL,
  `room_title` VARCHAR(45) NOT NULL,
  `room_content` VARCHAR(45) NOT NULL,
  `room_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `room_view` INT(45) NOT NULL,
  `horsehead` VARCHAR(45) NOT NULL,
  `org_filename` VARCHAR(150) NOT NULL,
  `save_filename` VARCHAR(150) NOT NULL,
  `filesize` BIGINT(20) NOT NULL,
  PRIMARY KEY (`room_num`, `commu_num`),
  INDEX `fk_ref_room_community1_idx` (`commu_num` ASC) VISIBLE,
  CONSTRAINT `fk_ref_room_community1`
    FOREIGN KEY (`commu_num`)
    REFERENCES `allchwi`.`community` (`commu_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`remit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`remit` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`remit` (
  `rem_num` INT(11) NOT NULL AUTO_INCREMENT,
  `pay_num` INT(11) NOT NULL,
  `rem_pay` INT(8) NOT NULL,
  `rem_bank` VARCHAR(45) NOT NULL,
  `rem_account` VARCHAR(100) NOT NULL,
  `rem_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `rem_status` INT(4) NOT NULL,
  `rem_revenue` INT(11) NOT NULL,
  PRIMARY KEY (`rem_num`, `pay_num`),
  INDEX `fk_remit_payment1_idx` (`pay_num` ASC) VISIBLE,
  CONSTRAINT `fk_remit_payment1`
    FOREIGN KEY (`pay_num`)
    REFERENCES `allchwi`.`payment` (`pay_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`sales` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`sales` (
  `sales_num` INT(11) NOT NULL AUTO_INCREMENT,
  `pay_num` INT(11) NOT NULL,
  `className` VARCHAR(45) NOT NULL,
  `tutorName` VARCHAR(45) NOT NULL,
  `pay` INT(11) NOT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `revenue` INT(11) NOT NULL,
  PRIMARY KEY (`sales_num`, `pay_num`),
  INDEX `fk_sales_payment1_idx` (`pay_num` ASC) VISIBLE,
  CONSTRAINT `fk_sales_payment1`
    FOREIGN KEY (`pay_num`)
    REFERENCES `allchwi`.`payment` (`pay_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 258
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `allchwi`.`wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allchwi`.`wishlist` ;

CREATE TABLE IF NOT EXISTS `allchwi`.`wishlist` (
  `wish_num` INT(11) NOT NULL AUTO_INCREMENT,
  `class_num` INT(11) NOT NULL,
  `ml_num` INT(11) NOT NULL,
  `wish_regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`wish_num`, `class_num`, `ml_num`),
  INDEX `fk_wishlist_class_info1_idx` (`class_num` ASC) VISIBLE,
  INDEX `fk_wishlist_member_login1_idx` (`ml_num` ASC) VISIBLE,
  CONSTRAINT `fk_wishlist_class_info1`
    FOREIGN KEY (`class_num`)
    REFERENCES `allchwi`.`class_info` (`class_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wishlist_member_login1`
    FOREIGN KEY (`ml_num`)
    REFERENCES `allchwi`.`member_login` (`ml_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
